[workspace]
members = ["contracts/*", "cw-*"]
exclude = ["contracts/test-migrated"]

resolver = "2"

[workspace.package]
authors = [
    "CyberHoward <cyberhoward@protonmail.com>",
    "Riada <riada@abstract.money>",
    "Abstract Money <contact@abstract.money>",
]
edition = "2021"
homepage = "https://abstract.money"
documentation = "https://docs.abstract.money/"
repository = "https://github.com/AbstractSDK/cw-packages"
license = "GPL-3.0-or-later"
keywords = ["cosmos", "cosmwasm", "framework"]

[workspace.dependencies]
cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../cosmwasm/packages/std" }
cw-address-like = { path = "../cw-plus-plus/packages/address-like" }
cw-storage-plus = { path = "../cw-storage-plus" }

[patch.'https://github.com/permissionlessweb/cw-packages']
cw-blob = { path = "contracts/cw-blob" }
cw-clearable = { path = "cw-clearable" }
