[workspace]
members = ["cw-*", "contracts/*"]

resolver = "2"

[workspace.package]
authors = [
    "CyberHoward <cyberhoward@protonmail.com>",
    "Riada <riada@abstract.money>",
    "Abstract Money <contact@abstract.money>",
]
edition = "2021"
homepage = "https://abstract.money"
documentation = "https://docs.abstract.money/"
repository = "https://github.com/AbstractSDK/cw-packages"
license = "GPL-3.0-or-later"
keywords = ["cosmos", "cosmwasm", "framework"]


[workspace.dependencies]
cosmwasm-schema = { path = "../ZK/cw/zk-cosmwasm/packages/schema" }
cw-storage-plus = { path = "../ZK/cw/zk-storage-plus" }
cosmwasm-std = { path = "../ZK/cw/zk-cosmwasm/packages/std" }
cw-address-like = { path = "../ZK/cw/zk-plus-plus/packages/address-like" }

