[package]
name = "cw-test-migrated"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false
description = "This contract used for testing migration from cw-blob with predictable address"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-blob = { path = "../cw-blob" }
cw-orch = { path = "../../../cw-orchestrator/cw-orch" }
cw-orch-clone-testing = { path = "../../../cw-orchestrator/packages/clone-testing" }
cw-orch-daemon = { path = "../../../cw-orchestrator/cw-orch-daemon" }

[dev-dependencies]
cosmrs = { path = "../../../cosmos-rust/cosmrs" }
cw-storage-plus = { workspace = true }

# Daemon test requires local juno to be running, after that use `cargo test --test daemon`
[[test]]
name = "daemon"
test = false
